name: Playwright Live Tests

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
  EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Project Setup
        uses: ./.github/actions/setup

      - uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      # Using ./test/next... is mandatory so we are not subject to playwright surprise updates
      - run: ./test/next/node_modules/.bin/playwright install --with-deps

      # https://github.com/patrickedqvist/wait-for-khulnasoft-preview
      # this allows to use action cache, which is not possible when using deployment_status otherwise
      # see https://github.com/actions/cache/issues/319
      - name: Wait for Khulnasoft Preview
        uses: patrickedqvist/wait-for-khulnasoft-preview@v1.3.1
        id: waitForKhulnasoftPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600

      - name: Run Integration Tests on Khulnasoft Preview
        run: pnpm integration-test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitForKhulnasoftPreview.outputs.url }}
          BLOB_UPLOAD_SECRET: ${{ secrets.BLOB_UPLOAD_SECRET }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-tests-live-report
          path: test/next/test-results
          retention-days: 30
