name: Quality

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
  EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: 'Prettier'
    runs-on: ubuntu-latest
    steps:
      - name: Project Setup
        uses: ./.github/actions/setup

      - name: Run Prettier check
        run: pnpm prettier-check

  eslint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: Project Setup
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: pnpm run lint

  types:
    name: 'TypeScript'
    runs-on: ubuntu-latest
    steps:
      - name: Project Setup
        uses: ./.github/actions/setup

      - name: Run TypeScript type check
        run: pnpm run type-check

  publint:
    name: 'publint'
    runs-on: ubuntu-latest
    steps:
      - name: Project Setup
        uses: ./.github/actions/setup

      - name: Run Publint
        run: pnpm run publint
